### ISSUE TITLE
Add `refresh: true`

### ISSUE THREAD

**Issue by pablgonz** [teatimeguest/setup-texlive-action#227]
This is related to issue #226 

You could implement a key `refresh: true | false`to rewrite the `cache`?

I followed the instructions in (https://docs.github.com/en/rest/actions/cache#delete-a-github-actions-cache-for-a-repository-using-a-cache-id) to solve the problem described in #226 and perhaps it can be implemented in a direct way.

Saludos

**Comment by teatimeguest** [comment]
I put a note in [README.md](https://github.com/teatimeguest/setup-texlive-action#caching) for now.

**Comment by pablgonz** [comment]
You are very fast, I don't know if it is related to this or not, if not I will delete it later (it's more of a doubt):

In (https://github.com/latex3/latex3/blob/main/.github/workflows/main.yaml) I read the following lines:

```yml
      # GitHub Actions don't regenerate the test if the key doesn't change, so
      # we integrate a random UUID into the key to keep them different.
      # DO NOT CHANGE THIS
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      # Actually load the cache. Since we never reuse the key, we need restore-keys
      # to indicate the prefix of our caches. This loads the newest cache with this
      # prefix in the key.
      #
      # If we want to force regeneration of the cache, increase the number after
      # *both* instances of "texlive-v"
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v1-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v1-
```

And they are somehow related to the way _cache_ and `l3build` are managed...does the current implementation have something like this...or does this have nothing to do here?

**Comment by teatimeguest** [comment]
`actions/cache` restores the most recent cache that matches the `restore-keys` if there is no cache that exactly matches the `key` ([docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)), so it is indeed possible to use the most updated cache every time in such a way. But, even though the directory is cached each time, each cache will be restored basically only once since the `key` never exactly matched, and I'm wondering if it is necessary to go that far. Also, if a flawed installation is cached due to an unexpected problem, as in the case #226, it would still need to be resolved manually even that way.

This action currently uses a cache key of the form:
```plain
setup-texlive-<os>-<architecture>-<texlive version>-<hash>
```
together with one restore-key:
```plain
setup-texlive-<os>-<architecture>-<texlive version>-
```
where the hash is generated from the names of packages to be installed. Therefore, if there is a cache with the same version and package list, it is used; otherwise, a cache with the same version is used if available. No new cache will be created unless you change the version or packages to install.

I couldn't see why l3build would require such a way...

**Comment by teatimeguest** [comment]
Sorry for it took so long.

After some consideration, I decided to add a cache update feature. It can be enabled by setting `SETUP_TEXLIVE_FORCE_UPDATE_CACHE` as follows:
```yaml
- uses: teatimeguest/setup-texlive-action@v2
  env:
    SETUP_TEXLIVE_FORCE_UPDATE_CACHE: 1
```

Please see [here](https://github.com/teatimeguest/setup-texlive-action#environment-variables) for more information.
