### ISSUE TITLE
pdflatex: command not found

### ISSUE THREAD

**Issue by yegor256** [teatimeguest/setup-texlive-action#233]
I'm doing this:

```
jobs:
  l3build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2
      - run: pdflatex --version
```

I'm getting:

```
Run pdflatex --version
/home/runner/work/_temp/b360[4](https://github.com/yegor256/iexec/actions/runs/3153250254/jobs/5129497651#step:5:5)3f5-765d-4bba-966c-37db9afa1556.sh: line 1: pdflatex: command not found
```

What is wrong?

**Comment by yegor256** [comment]
@teatimeguest please, help

**Comment by teatimeguest** [comment]
Thank you for using this action.

By default, the action only sets up `tlmgr` and does not install any other packages to fit fot CI use. The `pdflatex` command is included in the `latex-bin` package, so you need to install it.

In general, since `tlmgr` doesn't automatically install dependent packages, you will need to explicitly install many packages that you may not have paid attention to. If you don't know exactly all the packages you need, it is recommended to install `scheme-basic`, which contains most of the basic packages, including `latex-bin` and `l3build`.
```yaml
- uses: teatimeguest/setup-texlive-action@v2
  with:
    packages: scheme-basic
- run: pdflatex --version # OK
- run: l3build --version  # OK
```
