### ISSUE TITLE
Install latexmk?

### ISSUE THREAD

**Issue by samwilson** [teatimeguest/setup-texlive-action#252]
Is there an easy way to install latexmk with this action?

**Comment by teatimeguest** [comment]
This action is focused on setting up TeX Live, so there are no special functionality for `latexmk`, but it can probably be used by specifying an appropriate `packages` input:
```yaml
- name: Setup TeX Live
  uses: teatimeguest/setup-texlive-action@v2
  with:
    packages: >-
      scheme-basic
      latexmk
      # Other dependencies here

- name: Compile
  run: latexmk
```
