### ISSUE TITLE
Tex Live from `tlnet-archive` (roollback/pretest)

### ISSUE THREAD

**Issue by pablgonz** [teatimeguest/setup-texlive-action#289]
Hi, at the moment the historical versions of TeX Live are loaded from `https://ftp.math.utah.edu/pub/tex/historic/...` which stores the last updated version before it freezes and moves to the next version.

In general this is what one wants, but, in some situations it is necessary to test with a specific update date, either because of
kernel, package dependencies or other conflicts.

In [texlive.info](https://texlive.info/) we can find [tlnet-archive](https://texlive.info/tlnet-archive/) whose description is:

> _"a daily archive of all TeX Live packages updated since 2019-09-01, plus earlier final releases"_

from which you can install the versions by year and update date, including the _pretest_ version of this 2024.

I imagine something like:

```yml
- uses: teatimeguest/setup-texlive-action@v3
  with:
    version: 2024
    date: 2024/03/04
```

with which you could use the _pretest_ version, or something like:

```yml
- uses: teatimeguest/setup-texlive-action@v3
  with:
    version: 2022
    date: 2022/09/09
```

so that we can use an earlier version at a specific date.

While I understand the specific meaning is continuous CI integration, I think it would be a good addition (especially in the _pretest_ period of TeX Live).

Saludos

**Comment by teatimeguest** [comment]
Thanks for the suggestion! It sounds like a good idea.

I would like to add such a functionality, along with #283, to allow more flexibility in specifying a repository (but it might take some time as it would require several changes in the codebase).

**Comment by teatimeguest** [comment]
This feature has not been implemented yet, but you can now use `tlpretest` and daily archives by using the [`repository`](https://github.com/teatimeguest/setup-texlive-action/issues/283) input:

```yaml
- name: Use tlpretest
  uses: teatimeguest/setup-texlive-action@v3
  with:
    repository: https://ftp.math.utah.edu/pub/tlpretest/
    version: 2024
```

```yaml
- name: Use the archive as of 2024-01-01
  uses: teatimeguest/setup-texlive-action@v3
  with:
    repository: https://texlive.info/tlnet-archive/2024/01/01/tlnet/
```
