### ISSUE TITLE
How to translate apt-get install X into packages: X?

### ISSUE THREAD

**Issue by afuetterer** [teatimeguest/setup-texlive-action#308]
Hi there,

I am a new user of this action. I guess this not a really a question for this action, but maybe you can help me out?

I don't know how move from 

```yaml
run: sudo apt-get install --yes texlive-xetex
```

to

```yaml
- uses: teatimeguest/setup-texlive-action@v3
  with:
    packages: ???
```

What schemes or collections should I put here?

Thanks a lot.
