### ISSUE TITLE
Always failed with UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by PaleNeutron** [teatimeguest/setup-texlive-action#315]
```
Run teatimeguest/setup-texlive-action@v3
Restoring cache
Installation profile
Installing TeX Live
| InstallTLError: Failed to download install-tl
|     at download (setup-texlive-action/v3/packages/texlive/src/install-tl/cli.ts:185:19)
|     at acquire (setup-texlive-action/v3/packages/texlive/src/install-tl/cli.ts:116:[15](https://github.com/dexplo/dataframe_image/actions/runs/10844820731/job/30113460578#step:6:16))
|     at install2 (setup-texlive-action/v3/packages/action/src/runs/main/install.ts:43:21)
|     at setup-texlive-action/v3/packages/action/src/runs/main/index.ts:39:7 {
|   code: 'FAILED_TO_DOWNLOAD',
|   repository: 'https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet/',
|   [cause]: Error: unable to verify the first certificate
|    {
|     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
|   }
| }
Error: InstallTLError: Failed to download install-tl
```

See my action https://github.com/dexplo/dataframe_image/actions/runs/10844820731/job/30113460578

**Comment by PaleNeutron** [comment]
I found solution here https://github.com/teatimeguest/setup-texlive-action/issues/304#issuecomment-2171031060

**Comment by muzimuzhi** [comment]
I saw in https://github.com/dexplo/dataframe_image/commit/64cee1173bff9c7d898f63f082601d8256a24fcc you added `repository` and `version` inputs, so the step now becomes
```yaml
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        cache: true
        packages: >-
          scheme-basic
          collection-xetex
          collection-fontsrecommended
          collection-mathscience
          collection-pictures
          collection-latexextra
        repository: https://mirrors.tuna.tsinghua.edu.cn/tex-historic-archive/systems/texlive/2023/tlnet-final/
        version: 2023
```

Is the historic TeX Live 2023, rather than TeX Live 2024, really the version you want to use?
